# Python Data Structures Assignment.

'''
Assignment 1: List Manipulation
Task: Write a program that:

Creates a list of integers from 1 to 10.

Prints the list.

Appends the number 11 to the list.

Removes the first element of the list.

Prints the modified list.

Sorts the list in descending order and prints it
'''

In [1]:
import numpy as np
firstlist=np.arange(1,11)
print(firstlist)
firstlist=np.append(firstlist,11)
firstlist=np.delete(firstlist,0)
print(firstlist)
firstlist=firstlist[::-1]
print(firstlist)


[ 1  2  3  4  5  6  7  8  9 10]
[ 2  3  4  5  6  7  8  9 10 11]
[11 10  9  8  7  6  5  4  3  2]


In [2]:
#OR
firstlist1=[i for i in range(1,11) ]
print(firstlist1)
firstlist1.append(11)
print(firstlist1)
firstlist1.pop(0)
print(firstlist1)
firstlist1=firstlist1[::-1]
print(firstlist1)


[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11]
[2, 3, 4, 5, 6, 7, 8, 9, 10, 11]
[11, 10, 9, 8, 7, 6, 5, 4, 3, 2]


'''
Task: Write a program that:

Creates a dictionary with keys as the first five positive integers and values as their squares.

Prints the dictionary.

Updates the value of the key 3 to its cube.

Adds a new key-value pair (6, 36).

Removes the key-value pair for key 1.

Prints the updated dictionary
'''

In [3]:
#Using numpy lib 
import numpy as np
keys=['1','2','3','4','5']
values=[1,4,9,16,25]
firstdict =dict(zip(keys, values))
firstdict['3']=27
firstdict['6']=36

del firstdict['1']
print(firstdict)



{'2': 4, '3': 27, '4': 16, '5': 25, '6': 36}


In [4]:
#using dictionary comprehension here
firstdict1={x:x**2 for x in range(1,6)  }
print(firstdict1)
#using dictionary comprehension here won't work. so far.
# firstdict1 = dict([('1',1),('2',4),('3',9),('4',16),('5',25)])
# firstdict1
firstdict['3']=27
firstdict['6']=36

# del firstdict['1']
print(firstdict)

{1: 1, 2: 4, 3: 9, 4: 16, 5: 25}
{'2': 4, '3': 27, '4': 16, '5': 25, '6': 36}


'''
Assignment 3: Set Operations
Task: Write a program that:

Creates two sets of integers: Set A with {1, 2, 3, 4, 5} and Set B with {4, 5, 6, 7, 8}.

Prints the union of Set A and Set B.

Prints the intersection of Set A and Set B.

Prints the difference of Set A and Set B (elements in A but not in B).

Prints the symmetric difference (elements in A or B but not in both).
'''

In [5]:
SetA={x for x in range(1,6)}
print(SetA)
setB={x for x in range(4,9)}
print(SetA.union(setB))
print(SetA.intersection(setB))
print(SetA.difference(setB))
print(SetA.symmetric_difference(setB))


{1, 2, 3, 4, 5}
{1, 2, 3, 4, 5, 6, 7, 8}
{4, 5}
{1, 2, 3}
{1, 2, 3, 6, 7, 8}


'''
Assignment 4: Tuple Usage
Task: Write a program that:

Creates a tuple with the first five positive integers.

Prints the tuple.

Accesses and prints the third element of the tuple.

Attempts to change the second element of the tuple (expecting an error since tuples are immutable).

Converts the tuple to a list, modifies the second element, and converts it back to a tuple.
'''

In [6]:
tup=tuple(x for x in range(1,6))
print(tup)
tup[2]
# tup[1]=3
lstup=list(tup)
lstup[2]=10
tup=tuple(lstup)
print(tup)

(1, 2, 3, 4, 5)
(1, 2, 10, 4, 5)


'''Assignment 5: Nested Data Structures
Task: Write a program that:

Creates a list of dictionaries. Each dictionary represents a student with 'name', 'age', and 'grade' keys.

Adds three student dictionaries to the list.

Prints the list.

Iterates over the list and prints the name of each student who has a grade higher than 80.'''

In [7]:
Namedictls=[{'name':'Job', 'age1':25, 'grade':80},  {'name':'Kwame', 'age2':28,'grade':88}, {'name':'Kwesi', 'age3':20,'grade':89}]

Namedictls.append({'name':'Killer','age4':30,'grade':83}),
Namedictls.append({'name':'May','age5':23,'grade':46})
Namedictls.append({'name':'Mike', 'age6':23,'grade':65})
print(Namedictls)
for i in Namedictls:
    if i['grade']>80:
        print(i['name'])

[{'name': 'Job', 'age1': 25, 'grade': 80}, {'name': 'Kwame', 'age2': 28, 'grade': 88}, {'name': 'Kwesi', 'age3': 20, 'grade': 89}, {'name': 'Killer', 'age4': 30, 'grade': 83}, {'name': 'May', 'age5': 23, 'grade': 46}, {'name': 'Mike', 'age6': 23, 'grade': 65}]
Kwame
Kwesi
Killer
